### ISSUE TITLE
[bug] Variable Length CLI Parameters Passing 

### ISSUE THREAD

**Issue by nlchar** [cqfn/eo#196]
### The Problem
Say, we have such an example of a program that consumes variable-length CLI parameters.  
```
+package sandbox
+alias fibonacci sandbox.fibonacci
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf

[args...] > app
  stdout > @
    sprintf
      "%d\n%d\n%d\n%d\n%d\n"
      (args.get 0).toInt
      (args.get 1).toInt
      (args.get 2).toInt
      (args.get 3).toInt
      (args.get 4).toInt

```
For now, it does not run properly since the `run.sh` and `run.cmd` consider only the first CLI parameter.  
```
./run.sh 1 2 3 4 5
Exception in thread "main" java.lang.IllegalArgumentException: Can't get() the 1th element of the array, there are just 1 of them
	at org.eolang.EOarray$EOget.lambda$new$0(EOarray$EOget.java:53)
	at org.eolang.phi.AtLambda.lambda$copy$1(AtLambda.java:58)
	at org.eolang.phi.AtLambda.get(AtLambda.java:63)
	at org.eolang.phi.AtBound.get(AtBound.java:56)
	at org.eolang.phi.AtNamed.get(AtNamed.java:63)
	at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
	at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
	at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
	at org.eolang.phi.PhMethod.lambda$new$0(PhMethod.java:41)
	at org.eolang.phi.Data$Once.take(Data.java:58)
	at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
	at org.eolang.phi.Data$Take.take(Data.java:122)
	at org.eolang.txt.EOsprintf.lambda$new$0(EOsprintf.java:57)
	at org.eolang.phi.AtLambda.lambda$copy$1(AtLambda.java:58)
	at org.eolang.phi.AtLambda.get(AtLambda.java:63)
	at org.eolang.phi.AtBound.get(AtBound.java:56)
	at org.eolang.phi.AtNamed.get(AtNamed.java:63)
	at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
	at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
	at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
	at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
	at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
	at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
	at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
	at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
	at org.eolang.phi.Data$Take.take(Data.java:122)
	at org.eolang.phi.Data$Take.take(Data.java:127)
	at org.eolang.io.EOstdout.lambda$new$0(EOstdout.java:48)
	at org.eolang.phi.AtLambda.lambda$copy$1(AtLambda.java:58)
	at org.eolang.phi.AtLambda.get(AtLambda.java:63)
	at org.eolang.phi.AtBound.get(AtBound.java:56)
	at org.eolang.phi.AtNamed.get(AtNamed.java:63)
	at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
	at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
	at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
	at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
	at org.eolang.phi.Data$Take.take(Data.java:122)
	at org.eolang.phi.Data$Take.take(Data.java:127)
	at org.eolang.phi.Main.exec(Main.java:70)
	at org.eolang.phi.Main.main(Main.java:52)

```

**Comment by 0crat** [comment]
You @nlchar[/z](https://www.0crat.com/u/nlchar) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#196](https://github.com/cqfn/eo/issues/196); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
