### ISSUE TITLE
Unclear code behaviour

### ISSUE THREAD

**Issue by IngeniariusSoftware** [cqfn/eo#264]
Looks like the object is trying to substitute itself for input parameters when created

Code:
```
+package sandbox

+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf

[args...] > app

  if. > figure
    eq.
      args.length
      2
    rectangle
      (args.get 0).toInt
      (args.get 1).toInt
    circle
      (args.get 0).toInt

  stdout > @
    sprintf
      "%d"
      figure.area

[a b] > rectangle
  mul. > area
    a
    b

[r] > circle
  mul. > area
    3
    mul.
      r
      r

```

Error stack:

```
D:\Projects\Java\eo\sandbox>java -cp "target/classes;target/eo-runtime.jar" org.eolang.phi.Main sandbox.app 10 20
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Exception in thread "main" org.eolang.phi.Attr$Exception: Error at org.eolang.io.EOstdout#?
        at org.eolang.phi.AtNamed.get(AtNamed.java:66)
        at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
        at org.eolang.phi.Datarized.take(Datarized.java:53)
        at org.eolang.phi.Datarized.take(Datarized.java:65)
        at org.eolang.phi.Main.exec(Main.java:70)
        at org.eolang.phi.Main.main(Main.java:52)
Caused by: org.eolang.phi.Attr$Exception: Error at org.eolang.txt.EOsprintf#?
        at org.eolang.phi.AtNamed.get(AtNamed.java:66)
        at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.Datarized.take(Datarized.java:53)
        at org.eolang.phi.Datarized.take(Datarized.java:65)
        at org.eolang.io.EOstdout.lambda$new$0(EOstdout.java:49)
        at org.eolang.phi.AtLambda.lambda$copy$1(AtLambda.java:58)
        at org.eolang.phi.AtLambda.get(AtLambda.java:63)
        at org.eolang.phi.AtBound.get(AtBound.java:56)
        at org.eolang.phi.AtNamed.get(AtNamed.java:63)
        ... 8 more
Caused by: org.eolang.phi.Attr$Exception: Error at org.eolang.EOint$EOmul#?
        at org.eolang.phi.AtNamed.get(AtNamed.java:66)
        at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
        at org.eolang.phi.Datarized.take(Datarized.java:53)
        at org.eolang.txt.EOsprintf.lambda$new$0(EOsprintf.java:58)
        at org.eolang.phi.AtLambda.lambda$copy$1(AtLambda.java:58)
        at org.eolang.phi.AtLambda.get(AtLambda.java:63)
        at org.eolang.phi.AtBound.get(AtBound.java:56)
        at org.eolang.phi.AtNamed.get(AtNamed.java:63)
        ... 19 more
Caused by: org.eolang.phi.Attr$Exception: Error at sandbox.EOrectangle#?
        at org.eolang.phi.AtNamed.get(AtNamed.java:66)
        at org.eolang.phi.PhDefault$AtChild.get(PhDefault.java:178)
        at org.eolang.phi.Datarized.take(Datarized.java:53)
        at org.eolang.phi.Datarized.take(Datarized.java:65)
        at org.eolang.EOint$EOmul.lambda$new$0(EOint$EOmul.java:46)
        at org.eolang.phi.AtLambda.lambda$copy$1(AtLambda.java:58)
        at org.eolang.phi.AtLambda.get(AtLambda.java:63)
        at org.eolang.phi.AtBound.get(AtBound.java:56)
        at org.eolang.phi.AtNamed.get(AtNamed.java:63)
        ... 29 more
Caused by: org.eolang.phi.Attr$Exception: Can't get(), attribute "?" is absent
        at org.eolang.phi.AtAbsent.get(AtAbsent.java:58)
        at org.eolang.phi.AtNamed.get(AtNamed.java:63)
        ... 37 more
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#264](https://github.com/cqfn/eo/issues/264); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@IngeniariusSoftware I suspect the problem is similar to https://github.com/cqfn/eo/issues/201

**Comment by IngeniariusSoftware** [comment]
@yegor256  Incorrect encoding in the error stack is a small problem for me, I mean the reason that caused the error.  Runtime is trying to datarize the object, although I am requesting its attribute

**Comment by nlchar** [comment]
> @IngeniariusSoftware I suspect the problem is similar to #201

There is delta in the `?`.

**Comment by yegor256** [comment]
@nlchar yes, the `?` in the stack should be delta instead. Because of this, the runtime doesn't work, I believe.

**Comment by IngeniariusSoftware** [comment]
@nlchar yes, delta. @yegor256 why is the object trying to datarize? The problem is not with the encoding because I implement some like this in circle:
```
"23" > @
```
and It will be work, but this value begins to replace the input parameter of the object itself, this is some kind of magic

**Comment by yegor256** [comment]
@IngeniariusSoftware I can't understand the question. It's better to submit a ticket in a traditional format: "what you do, what you expect, what you get instead"

**Comment by IngeniariusSoftware** [comment]
@yegor256
What you do? - Check simple example of duck typing on the example of geometric shapes.
What you expect? - Expecting the value of the area of the figure to the console output.
What you get instead? - Error stack.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#264](https://github.com/cqfn/eo/issues/264); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#264](https://github.com/cqfn/eo/issues/264); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#264](https://github.com/cqfn/eo/issues/264); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#264](https://github.com/cqfn/eo/issues/264); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#264](https://github.com/cqfn/eo/issues/264); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#264](https://github.com/cqfn/eo/issues/264); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#264](https://github.com/cqfn/eo/issues/264); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#264](https://github.com/cqfn/eo/issues/264); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#264](https://github.com/cqfn/eo/issues/264); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#264](https://github.com/cqfn/eo/issues/264); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#264](https://github.com/cqfn/eo/issues/264); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
