### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by eyihluyc** [cqfn/eo#299]
Steps to reproduce:
`git clone https://github.com/cqfn/eo.git`
`mvn clean install`

Error logs:
```[INFO] --- jcabi-maven-plugin:0.14.1:versionalize (jcabi-versionalize-packages) @ eo-parser ---
[INFO] jcabi-aspects 0.18/55a5c13 started new daemon thread jcabi-loggable for watching of @Loggable annotated methods
[INFO] Versionalizing C:\Users\Violetta\IdeaProjects\eo\eo-parser\target\classes directory
[INFO] org.hibernate.validator.internal.util.Version: HV000001: Hibernate Validator 5.1.2.Final
[ERROR] JSR-303 validator thrown during initialization: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:515)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:423)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:417)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:689)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:416)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:425)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:110)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:86)
	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:41)
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:276)
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:110)
	at com.jcabi.aspects.aj.MethodValidator.build(MethodValidator.java:323)
	at com.jcabi.aspects.aj.MethodValidator.<init>(MethodValidator.java:81)
	at com.jcabi.aspects.aj.MethodValidator.ajc$postClinit(MethodValidator.java:1)
	at com.jcabi.aspects.aj.MethodValidator.<clinit>(MethodValidator.java:1)
	at com.jcabi.maven.plugin.VersionalizeMojo.versionalize(VersionalizeMojo.java:157)
	at com.jcabi.maven.plugin.VersionalizeMojo.execute_aroundBody0(VersionalizeMojo.java:111)
	at com.jcabi.maven.plugin.VersionalizeMojo$AjcClosure1.run(VersionalizeMojo.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.jcabi.maven.plugin.VersionalizeMojo.execute_aroundBody2(VersionalizeMojo.java:98)
	at com.jcabi.maven.plugin.VersionalizeMojo$AjcClosure3.run(VersionalizeMojo.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.jcabi.maven.plugin.VersionalizeMojo.execute(VersionalizeMojo.java:98)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 56 more
```

```
[ERROR] Errors: 
[ERROR]   CompileMojoTest.testRealCompilation:60->compile:84 » Parsing [1:0] mismatched ...
[ERROR]   SnippetTest.testFullRun:72->run:147->lambda$run$1:147->javac:201 » IllegalArgument
[ERROR]   SnippetTest.testFullRun:72->run:147->lambda$run$1:147->javac:201 » IllegalArgument
[ERROR]   SnippetTest.testFullRun:72->run:147->lambda$run$1:147->javac:201 » IllegalArgument
[ERROR]   SnippetTest.testFullRun:72->run:147->lambda$run$1:147->javac:201 » IllegalArgument
[INFO]
[ERROR] Tests run: 16, Failures: 0, Errors: 5, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for eo-parent 1.0-SNAPSHOT:
[INFO]
[INFO] eo-parent .......................................... SUCCESS [  3.025 s]
[INFO] eo-parser .......................................... SUCCESS [ 22.015 s]
[INFO] eo-maven-plugin .................................... FAILURE [ 53.851 s]
[INFO] eo-runtime ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:19 min
[INFO] Finished at: 2021-06-14T20:36:53+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project eo-maven-plugin: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Violetta\IdeaProjects\eo\eo-maven-plugin\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :eo-maven-plugin
```

System specs:
`mvn -v`
`Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: C:\apache-maven-3.8.1\bin\..
Java version: 12.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-12.0.2
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"`

**Comment by yegor256** [comment]
@eyihluyc I believe this bug is fixed already
