### ISSUE TITLE
Problem with binding

### ISSUE THREAD

**Issue by someilay** [cqfn/eo#304]
Code 1:
```eolang
+package sandbox
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf

[] > animal
  stdout > say
    "Animal's sound!\n"

animal > lion

[args...] > app
  lion.say > @
```
Code 2:
```eolang
+package sandbox
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf

[] > animal
  stdout > say
    "Animal's sound!\n"

[args...] > app
  animal > lion
  lion.say > @
```
Code 1 causes runtime error:

```
Caused by: org.eolang.phi.Attr$Exception: Can't get(), attribute "say" is absent
        at org.eolang.phi.AtAbsent.get(AtAbsent.java:58)
        at org.eolang.phi.AtNamed.get(AtNamed.java:63)
        ... 8 more
```

Code 2 works as expected.
Why is it so?

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.31`

**Comment by yegor256** [comment]
@someilay it was a bug, I fixed it. Please check.

**Comment by yegor256** [comment]
@someilay I'm closing. If you think the bug is still there, please open a new issue.
