### ISSUE TITLE
The problem to use recursion with external "variables"

### ISSUE THREAD

**Issue by kreofil** [cqfn/eo#337]
Имеются проблемы с выходом из рекурсий при имитации работы с глобальными переменными. Делалась попытка имитации следующего кода на C:

```    #include <stdio.h>
    #include <stdlib.h>

    int n;
    int result = 1;

    void factorial() {
        if(n < 2) {
            return;
        } else {
            result = result * n;
            n = n - 1;
            factorial();
        }
    }

    int main(int argc, char** argv) {
        n = atoi(argv[1]);
        printf("%d! = ", n);
        factorial();
        printf("%d\n", result);
    }
```

Имитация кодогенерации вылетела при возврате из рекурсии. Ниже приводится упрощенная верси на Eolang, демонстрирующая эту проблему.

```
        +package factGlobalTest

        +alias stdout org.eolang.io.stdout
        +alias sprintf org.eolang.txt.sprintf

        [arg] > factorialN
          memory > n!
          memory > result!

          # Factorial evaluation
          [] > factorial
            seq > @
              if.
                less.
                  ^.n
                  2
                seq
                  stdout
                    sprintf
                      "%d\n"
                      ^.result
                  stdout
                    "OK\n"
                seq
                  ^.result.write
                    mul.
                      ^.result
                      ^.n
                  ^.n.write
                    sub.
                      ^.n
                      1
                  factorial

          # Main function
          [arg] > main
            seq > @
              ^.n.write (arg.get 0).toInt
              stdout
                sprintf
                  "%d! = "
                  ^.n
              ^.factorial

          seq > @
            n.write 0
            result.write 1
            main arg


        # Старт приложения
        [args...] > app
          seq > @
            factorialN args
```
В результат выполнения факториал вычисляется, но при возврате из рекурсий программа завершается некорректно. Исключение при вычислении 1!, когда рекурсия отсутствует:

```
        $ ./run.sh 2
        2! = 2
        OK
        Exception in thread "main" org.eolang.phi.Attr$Exception: Error at org.eolang.EOseq#φ
                at org.eolang.phi.AtNamed.get(AtNamed.java:66)
                at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
                at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
                at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
                at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
                at org.eolang.phi.Datarized.take(Datarized.java:53)
                at org.eolang.phi.Datarized.take(Datarized.java:65)
                at org.eolang.phi.Main.exec(Main.java:70)
                at org.eolang.phi.Main.main(Main.java:52)
        Caused by: org.eolang.phi.Attr$Exception: Error at org.eolang.EOseq#φ
                at org.eolang.phi.AtNamed.get(AtNamed.java:66)
                at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
                at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
                at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
                at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
                at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
                at org.eolang.phi.PhDefault.attr(PhDefault.java:134)
                at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
                at org.eolang.phi.PhOnce.attr(PhOnce.java:65)
                at org.eolang.phi.Datarized.take(Datarized.java:53)
                at org.eolang.EOseq.lambda$new$0(EOseq.java:55)
                at org.eolang.phi.AtLambda.lambda$copy$1(AtLambda.java:58)
                at org.eolang.phi.AtLambda.get(AtLambda.java:63)
                at org.eolang.phi.AtBound.get(AtBound.java:56)
                at org.eolang.phi.AtNamed.get(AtNamed.java:63)
                . 8 more
            .....
```

**Comment by yegor256** [comment]
@kreofil я не могу повторить ошибку. У меня все ок работает и ошибки нет. Попробуйте еще раз с версией 0.6.2.

**Comment by yegor256** [comment]
@kreofil закрываю. Если ошибка повторится, откройте пожалуйста новый тикет.

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#337` is not assigned, can't get performer
