### ISSUE TITLE
jcabi-maven-plugin throws java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by andreoss** [cqfn/eo#404]
```
16:40:11,532 [INFO] --- jcabi-maven-plugin:0.14.1:versionalize (jcabi-versionalize-packages) @ eo-parser ---
16:40:11,802 [INFO] jcabi-aspects 0.18/55a5c13 started new daemon thread jcabi-loggable for watching of @Loggable annotated methods
16:40:11,808 [INFO] Versionalizing /home/a/w/eo/eo/eo-parser/target/classes directory
[INFO] org.hibernate.validator.internal.util.Version: HV000001: Hibernate Validator 5.1.2.Final
16:40:11,967 [ERROR] JSR-303 validator thrown during initialization: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
	at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:110)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:86)
	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:41)
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:276)
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:110)
	at com.jcabi.aspects.aj.MethodValidator.build(MethodValidator.java:323)
	at com.jcabi.aspects.aj.MethodValidator.<init>(MethodValidator.java:81)
	at com.jcabi.aspects.aj.MethodValidator.ajc$postClinit(MethodValidator.java:1)
	at com.jcabi.aspects.aj.MethodValidator.<clinit>(MethodValidator.java:1)
	at com.jcabi.maven.plugin.VersionalizeMojo.versionalize(VersionalizeMojo.java:157)
	at com.jcabi.maven.plugin.VersionalizeMojo.execute_aroundBody0(VersionalizeMojo.java:111)
	at com.jcabi.maven.plugin.VersionalizeMojo$AjcClosure1.run(VersionalizeMojo.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.jcabi.maven.plugin.VersionalizeMojo.execute_aroundBody2(VersionalizeMojo.java:98)
	at com.jcabi.maven.plugin.VersionalizeMojo$AjcClosure3.run(VersionalizeMojo.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.jcabi.maven.plugin.VersionalizeMojo.execute(VersionalizeMojo.java:98)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
```

**Comment by yegor256** [comment]
@andreoss I know. I tried to fix the plugin, but no luck :( Interested in fixing it?

**Comment by yegor256** [comment]
@andreoss I believe it's fixed?

**Comment by andreoss** [comment]
@yegor256 yes, should be closed

El 24 de diciembre de 2021 4:50:04 a. m. GMT-03:00, Yegor Bugayenko ***@***.***> escribió:
***@***.*** I believe it's fixed?
