### ISSUE TITLE
floating point exception syntax is not supported

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#406]
Try to add this code to `full-syntax.yaml`:

```
2.4e-34 > x
```

It should be parsed as a float, but it fails.

We should support Java floating-point numbers format.

**Comment by yegor256** [comment]
@andreoss please, fix this, the budget is 0.5h

**Comment by yegor256** [comment]
@andreoss I will assign this to someone else, ignore this task please

**Comment by yegor256** [comment]
@Graur can you please try to help us here?

**Comment by Graur** [comment]
Sure, I will try to help here, thanks!

**Comment by Graur** [comment]
I think that I can reproduce this error now. This happens with stacktrace:
```
org.eolang.parser.ParsingException: [62:3] missing EOL at 'e-34': 2.4e-34 > x"
	at org.eolang.parser.Syntax$1.syntaxError(Syntax.java:102)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportMissingToken(DefaultErrorStrategy.java:409)
	at org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenInsertion(DefaultErrorStrategy.java:519)
	at org.antlr.v4.runtime.DefaultErrorStrategy.recoverInline(DefaultErrorStrategy.java:476)
	at org.antlr.v4.runtime.Parser.match(Parser.java:206)
	at org.eolang.parser.ProgramParser.objects(ProgramParser.java:368)
	at org.eolang.parser.ProgramParser.program(ProgramParser.java:164)
	at org.eolang.parser.Syntax.parse(Syntax.java:126)
```

**Comment by Graur** [comment]
I noticed a broken link at the end of the "Quik start" part in the main README.md file.
I think it can be changed from https://github.com/cqfn/eo/tree/master/eo-maven-plugin/src/it to https://github.com/cqfn/eo/tree/master/eo-maven-plugin/src/it-disabled. Or something else.
@yegor256 Is it right?

**Comment by yegor256** [comment]
@yegor256 you better report such questions in separate tickets

**Comment by Graur** [comment]
Pull request number is [#548](https://github.com/cqfn/eo/pull/548)

**Comment by yegor256** [comment]
@Graur thanks!
