### ISSUE TITLE
Bug with while

### ISSUE THREAD

**Issue by someilay** [cqfn/eo#426]
I have the following code from readme.
```
+package sandbox
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf

[args...] > app
  memory > x
  seq > @
    x.write 2
    while.
      x.less 6
      [i]
        seq > @
          stdout
            sprintf "%dx%d = %d\n" x x (x.pow 2)
          x.write (x.add 1)
```

Exception during runtime:
2x2 = 4
3x3 = 9
4x4 = 16
5x5 = 25
Exception in thread "main" java.lang.ClassCastException: Cannot cast java.lang.Long to java.lang.Boolean
        at java.base/java.lang.Class.cast(Class.java:3818)
        at org.eolang.Dataized.take(Dataized.java:82)
        at org.eolang.Main.exec(Main.java:86)
        at org.eolang.Main.main(Main.java:60)

**Comment by yegor256** [comment]
@someilay I fixed the doc in fd8c2b80, thanks for reporting!
