### ISSUE TITLE
Copying object in seq

### ISSUE THREAD

**Issue by someilay** [cqfn/eo#498]
Code 1:
```
+package sandbox
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf
+alias org.eolang.gray.cage

[] > test

[args...] > app
  cage > a
  seq > @
    a.write
      test
    stdout
      "Done!\n"
```
Code 2:
```
+package sandbox
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf
+alias org.eolang.gray.cage

[] > test

[args...] > app
  cage > a
  seq > @
    test
    stdout
      "Done!\n"

```

Code 1 runs without any errors.
Code 2 produces following error:
```
Exception in thread "main" org.eolang.Attr$StillAbstractException: The attribute is not initialized, can't read
	at org.eolang.AtFree.get(AtFree.java:83)
	at org.eolang.CachedPhi.get(CachedPhi.java:74)
	at org.eolang.PhDefault.attr(PhDefault.java:208)
	at org.eolang.Dataized.take(Dataized.java:71)
	at EOorg.EOeolang.EOseq.lambda$new$0(EOseq.java:56)
	at org.eolang.AtComposite.lambda$toData$0(AtComposite.java:88)
	at org.eolang.AtComposite.get(AtComposite.java:68)
	at org.eolang.CachedPhi.get(CachedPhi.java:74)
	at org.eolang.PhDefault.attr(PhDefault.java:208)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhDefault.attr(PhDefault.java:208)
	at org.eolang.Dataized.take(Dataized.java:71)
	at org.eolang.Dataized.take(Dataized.java:110)
	at org.eolang.Main.run(Main.java:166)
	at org.eolang.Main.main(Main.java:91)
```

Why does it happen?

**Comment by yegor256** [comment]
@someilay you can't dataize `test`, it doesn't have `@`. In the first snippet you don't dataize it, you only dataize the `write` object, which returns TRUE

**Comment by 0crat** [comment]
Job `gh:cqfn/eo#498` is not assigned, can't get performer
