### ISSUE TITLE
Single-line abstraction syntax fails to parse

### ISSUE THREAD

**Issue by nikololiahim** [cqfn/eo#584]
### Problematic Code (example from [paper](https://arxiv.org/pdf/2111.13384.pdf), section 2.9)
```
(dir "/tmp").walk
  * ([f] (f.is-dir > @))
```
### Parser Error Message:
```
[2:5] no viable alternative at input ' ([': "  * ([f] (f.is-dir > @))"
org.eolang.parser.ParsingException: [2:5] no viable alternative at input ' ([': "  * ([f] (f.is-dir > @))"
	at org.eolang.parser.Syntax$1.syntaxError(Syntax.java:102)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
	at org.eolang.parser.ProgramParser.htail(ProgramParser.java:1459)
```

**Comment by andreoss** [comment]
@yegor256 Ready to take that.

**Comment by yegor256** [comment]
@andreoss please, go ahead

**Comment by 0crat** [comment]
@andreoss[/z](https://www.0crat.com/u/andreoss) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@nikololiahim this seems to be fixed. If not, open a new issue pls.

**Comment by 0crat** [comment]
@andreoss[/z](https://www.0crat.com/u/andreoss) resigned from [#584](https://github.com/cqfn/eo/issues/584), since the job is not in scope anymore
