### ISSUE TITLE
Bitwise AND does not work

### ISSUE THREAD

**Issue by someilay** [cqfn/eo#592]
Code:

```
+package sandbox
+alias org.eolang.io.stdout

[args...] > main
  seq > @
    stdout
      as-string.
        as-int.
          and.
            as-bytes.
              1
            as-bytes.
              1
    stdout
      "\n"
```

Execution output:
```
Exception in thread "main" java.nio.BufferUnderflowException
	at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:706)
	at java.base/java.nio.HeapByteBuffer.getLong(HeapByteBuffer.java:485)
	at EOorg.EOeolang.EObytes$EOas_int.lambda$new$0(EObytes$EOas_int.java:47)
	at org.eolang.AtComposite.get(AtComposite.java:73)
	at org.eolang.CachedPhi.get(CachedPhi.java:81)
	at org.eolang.PhDefault.attr(PhDefault.java:226)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhMethod.lambda$new$0(PhMethod.java:42)
	at org.eolang.Data$Once.take(Data.java:95)
	at org.eolang.PhOnce.equals(PhOnce.java:61)
	at org.eolang.PhMethod.equals(PhMethod.java:32)
	at org.eolang.AtFree.get(AtFree.java:82)
	at org.eolang.AtNamed.get(AtNamed.java:75)
	at org.eolang.Param.weak(Param.java:97)
	at org.eolang.Param.strong(Param.java:77)
	at EOorg.EOeolang.EOio.EOstdout.lambda$new$0(EOstdout.java:54)
	at org.eolang.AtComposite.get(AtComposite.java:73)
	at org.eolang.CachedPhi.get(CachedPhi.java:81)
	at org.eolang.PhDefault.attr(PhDefault.java:226)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.Dataized.take(Dataized.java:81)
	at EOorg.EOeolang.EOseq.lambda$new$0(EOseq.java:51)
	at org.eolang.AtComposite.get(AtComposite.java:73)
	at org.eolang.CachedPhi.get(CachedPhi.java:81)
	at org.eolang.PhDefault.attr(PhDefault.java:226)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhDefault.attr(PhDefault.java:226)
	at org.eolang.Dataized.take(Dataized.java:81)
	at org.eolang.Dataized.take(Dataized.java:122)
	at org.eolang.Main.run(Main.java:166)
	at org.eolang.Main.main(Main.java:91)
```

**Comment by yegor256** [comment]
@andreoss can you take a look, please?

**Comment by andreoss** [comment]
@yegor256 Yes.

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.10`

**Comment by yegor256** [comment]
@someilay try version 0.21.10, should work
