### ISSUE TITLE
While loop still does not work 

### ISSUE THREAD

**Issue by someilay** [cqfn/eo#593]
Code:
```
+package sandbox
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf

[args...] > main
  memory > x
  and. > @
    x.write 2
    while.
      x.less 6
      [i]
        seq > @
          stdout
            sprintf "%dx%d = %d\n" x x (x.pow 2)
          x.write (x.add 1)
```

Execution result:
```
2x2 = 4
3x3 = 9
4x4 = 16
5x5 = 25
6x6 = 36
Exception in thread "main" java.lang.IllegalArgumentException: The 0th argument of 'and' is of type java.lang.Long, not Boolean
	at EOorg.EOeolang.EObool$EOand.lambda$new$0(EObool$EOand.java:57)
	at org.eolang.AtComposite.get(AtComposite.java:73)
	at org.eolang.CachedPhi.get(CachedPhi.java:81)
	at org.eolang.PhDefault.attr(PhDefault.java:226)
	at org.eolang.PhNamed.attr(PhNamed.java:92)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhOnce.attr(PhOnce.java:96)
	at org.eolang.PhDefault.attr(PhDefault.java:226)
	at org.eolang.Dataized.take(Dataized.java:81)
	at org.eolang.Dataized.take(Dataized.java:122)
	at org.eolang.Main.run(Main.java:166)
	at org.eolang.Main.main(Main.java:91)
```

**Comment by yegor256** [comment]
@someilay try replacing `and` with `seq`:

```
+package sandbox
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf

[args...] > main
  memory > x
  seq. > @
    x.write 2
    while.
      x.less 6
      [i]
        seq > @
          stdout
            sprintf "%dx%d = %d\n" x x (x.pow 2)
          x.write (x.add 1)
```

**Comment by yegor256** [comment]
@someilay this should work:

```
+package sandbox
+alias org.eolang.io.stdout
+alias org.eolang.txt.sprintf

[args...] > main
  memory > x
  seq > @
    x.write 2
    while.
      x.less 6
      [i]
        seq > @
          stdout
            sprintf "%dx%d = %d\n" x x (x.pow 2)
          x.write (x.add 1)
    TRUE
```

It is expected that `main` dataizes to a boolean data.
